//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.DesktopServices {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.DesktopServices.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   1 study has failed to load. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatStudyLoadFailure {
            get {
                return ResourceManager.GetString("MessageFormatStudyLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} studies failed to load. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatStudyLoadFailures {
            get {
                return ResourceManager.GetString("MessageFormatStudyLoadFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 study had one or more images that failed to load. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePartialStudyLoadFailure {
            get {
                return ResourceManager.GetString("MessagePartialStudyLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} studies had one or more images that failed to load. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePartialStudyLoadFailures {
            get {
                return ResourceManager.GetString("MessagePartialStudyLoadFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please see the logs for more details. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePleaseSeeLogs {
            get {
                return ResourceManager.GetString("MessagePleaseSeeLogs", resourceCulture);
            }
        }
    }
}
