//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Tools.Measurement {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Tools.Measurement.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Calibrate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CalibrationDialogTitle {
            get {
                return ResourceManager.GetString("CalibrationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Elliptical ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandCreateEllipiticalRoi {
            get {
                return ResourceManager.GetString("CommandCreateEllipiticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Polygonal ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandCreatePolygonalRoi {
            get {
                return ResourceManager.GetString("CommandCreatePolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Protractor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandCreateProtractor {
            get {
                return ResourceManager.GetString("CommandCreateProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Rectangle ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandCreateRectangleRoi {
            get {
                return ResourceManager.GetString("CommandCreateRectangleRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Ruler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandCreateRuler {
            get {
                return ResourceManager.GetString("CommandCreateRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot calibrate a ruler of zero-length. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ErrorCannotCalibrateZeroLengthRuler {
            get {
                return ResourceManager.GetString("ErrorCannotCalibrateZeroLengthRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ellipse {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatEllipseName {
            get {
                return ResourceManager.GetString("FormatEllipseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polygon {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatPolygonName {
            get {
                return ResourceManager.GetString("FormatPolygonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protractor {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatProtractorName {
            get {
                return ResourceManager.GetString("FormatProtractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangle {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatRectangleName {
            get {
                return ResourceManager.GetString("FormatRectangleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ruler {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatRulerName {
            get {
                return ResourceManager.GetString("FormatRulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibrate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuCalibrationTool {
            get {
                return ResourceManager.GetString("MenuCalibrationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elliptical ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuEllipticalRoi {
            get {
                return ResourceManager.GetString("MenuEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measurement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuMeasurement {
            get {
                return ResourceManager.GetString("MenuMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polygonal ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuPolygonalRoi {
            get {
                return ResourceManager.GetString("MenuPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protractor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuProtractor {
            get {
                return ResourceManager.GetString("MenuProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangular ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuRectangularRoi {
            get {
                return ResourceManager.GetString("MenuRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ruler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuRuler {
            get {
                return ResourceManager.GetString("MenuRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Angles benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuShowAngles {
            get {
                return ResourceManager.GetString("MenuShowAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Length must be greater than 0 cm. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageInvalidLength {
            get {
                return ResourceManager.GetString("MessageInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   N/A benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elliptical ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarEllipticalRoi {
            get {
                return ResourceManager.GetString("ToolbarEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polygonal ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarPolygonalRoi {
            get {
                return ResourceManager.GetString("ToolbarPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protractor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarProtractor {
            get {
                return ResourceManager.GetString("ToolbarProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangular ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarRectangularRoi {
            get {
                return ResourceManager.GetString("ToolbarRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ruler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarRuler {
            get {
                return ResourceManager.GetString("ToolbarRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Angles benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarShowAngles {
            get {
                return ResourceManager.GetString("ToolbarShowAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:F1}° benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolsMeasurementFormatDegrees {
            get {
                return ResourceManager.GetString("ToolsMeasurementFormatDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibrate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipCalibrationTool {
            get {
                return ResourceManager.GetString("TooltipCalibrationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elliptical ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipEllipticalRoi {
            get {
                return ResourceManager.GetString("TooltipEllipticalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polygonal ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipPolygonalRoi {
            get {
                return ResourceManager.GetString("TooltipPolygonalRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protractor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipProtractor {
            get {
                return ResourceManager.GetString("TooltipProtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rectangular ROI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipRectangularRoi {
            get {
                return ResourceManager.GetString("TooltipRectangularRoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ruler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipRuler {
            get {
                return ResourceManager.GetString("TooltipRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Angles benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipShowAngles {
            get {
                return ResourceManager.GetString("TooltipShowAngles", resourceCulture);
            }
        }
    }
}
