//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BoolNo {
            get {
                return ResourceManager.GetString("BoolNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BoolYes {
            get {
                return ResourceManager.GetString("BoolYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandChange {
            get {
                return ResourceManager.GetString("CommandChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create multiline graphic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandCreateMultilineGraphic {
            get {
                return ResourceManager.GetString("CommandCreateMultilineGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create rectangle graphic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandCreateRectangleGraphic {
            get {
                return ResourceManager.GetString("CommandCreateRectangleGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create ROI graphic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandCreateROIGraphic {
            get {
                return ResourceManager.GetString("CommandCreateROIGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandDelete {
            get {
                return ResourceManager.GetString("CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Text benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandEditText {
            get {
                return ResourceManager.GetString("CommandEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandMove {
            get {
                return ResourceManager.GetString("CommandMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move control point benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandMoveControlPoint {
            get {
                return ResourceManager.GetString("CommandMoveControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move graphic benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandMoveGraphic {
            get {
                return ResourceManager.GetString("CommandMoveGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resize benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandResize {
            get {
                return ResourceManager.GetString("CommandResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stretch benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandStretch {
            get {
                return ResourceManager.GetString("CommandStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionBlueColorMap {
            get {
                return ResourceManager.GetString("DescriptionBlueColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (None) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionGrayscaleColorMap {
            get {
                return ResourceManager.GetString("DescriptionGrayscaleColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionGreenColorMap {
            get {
                return ResourceManager.GetString("DescriptionGreenColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Palette Color benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionPaletteColorMap {
            get {
                return ResourceManager.GetString("DescriptionPaletteColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefetches image data in a display set when display set becomes visible. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionPrefetchingStrategyVisibleDisplaySet {
            get {
                return ResourceManager.GetString("DescriptionPrefetchingStrategyVisibleDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Presentation Lut benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionPresentationLut {
            get {
                return ResourceManager.GetString("DescriptionPresentationLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionRedColorMap {
            get {
                return ResourceManager.GetString("DescriptionRedColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1/centimetre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnits1cm {
            get {
                return ResourceManager.GetString("DescriptionUnits1cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   becquerels/millilitre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsBqml {
            get {
                return ResourceManager.GetString("DescriptionUnitsBqml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   square centimetre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsCm2 {
            get {
                return ResourceManager.GetString("DescriptionUnitsCm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   square centimetre/millilitre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsCm2ml {
            get {
                return ResourceManager.GetString("DescriptionUnitsCm2ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   counts benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsCnts {
            get {
                return ResourceManager.GetString("DescriptionUnitsCnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   counts/second benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsCps {
            get {
                return ResourceManager.GetString("DescriptionUnitsCps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   grams/millilitre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsGml {
            get {
                return ResourceManager.GetString("DescriptionUnitsGml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hounsfield units benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsHU {
            get {
                return ResourceManager.GetString("DescriptionUnitsHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   milligrams/minute/millilitre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsMgminml {
            get {
                return ResourceManager.GetString("DescriptionUnitsMgminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   millilitre/grams benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsMlg {
            get {
                return ResourceManager.GetString("DescriptionUnitsMlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   millilitre/minute/grams benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsMlming {
            get {
                return ResourceManager.GetString("DescriptionUnitsMlming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   millilitre/minute/millilitre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsMlminml {
            get {
                return ResourceManager.GetString("DescriptionUnitsMlminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   millilitre/millilitre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsMlml {
            get {
                return ResourceManager.GetString("DescriptionUnitsMlml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1/1000 optical density benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsOD {
            get {
                return ResourceManager.GetString("DescriptionUnitsOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   percent benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsPcnt {
            get {
                return ResourceManager.GetString("DescriptionUnitsPcnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   proportional to counts benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsPropcnts {
            get {
                return ResourceManager.GetString("DescriptionUnitsPropcnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   proportional to counts/second benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsPropcps {
            get {
                return ResourceManager.GetString("DescriptionUnitsPropcps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   standard deviations benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsStddev {
            get {
                return ResourceManager.GetString("DescriptionUnitsStddev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   micromoles/minute/millilitre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsUmolminml {
            get {
                return ResourceManager.GetString("DescriptionUnitsUmolminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   micromoles/millilitre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsUmolml {
            get {
                return ResourceManager.GetString("DescriptionUnitsUmolml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   unknown benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionUnitsUnspecified {
            get {
                return ResourceManager.GetString("DescriptionUnitsUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additional mouse tool assignments must be modified ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionAdditionalMouseToolAssignmentsMustBeModified {
            get {
                return ResourceManager.GetString("ExceptionAdditionalMouseToolAssignmentsMustBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AnnotationItem has no display name: {0}. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionFormatAnnotationItemHasNoDisplayName {
            get {
                return ResourceManager.GetString("ExceptionFormatAnnotationItemHasNoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImageBufferWin32 is not supported on non-Win32 platforms. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionImageBufferWin32NotSupported {
            get {
                return ResourceManager.GetString("ExceptionImageBufferWin32NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image is not grayscale. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionImageIsNotGrayscale {
            get {
                return ResourceManager.GetString("ExceptionImageIsNotGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid pixel data (expected size: {0} bytes, actual size: {1} bytes). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionIncorrectPixelDataSize {
            get {
                return ResourceManager.GetString("ExceptionIncorrectPixelDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Annotation Layout XML ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidAnnotationLayoutXml {
            get {
                return ResourceManager.GetString("ExceptionInvalidAnnotationLayoutXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Filtered Annotation Layout XML ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidFilteredAnnotationLayoutXml {
            get {
                return ResourceManager.GetString("ExceptionInvalidFilteredAnnotationLayoutXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ({0},{1},{2},{3}) is an invalid normalized rectangle.  Normalized rectangle coordinates must be between 0.0 and 1.0 with Right &gt; Left, Bottom &gt; Top. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidNormalizedRectangle {
            get {
                return ResourceManager.GetString("ExceptionInvalidNormalizedRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ({0},{1},{2},{3}) is an invalid parent rectangle.  Parent rectangle must be such that all coordinates are positive with Right &gt; Left, Bottom &gt; Top. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidParentRectangle {
            get {
                return ResourceManager.GetString("ExceptionInvalidParentRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patient ID must not be empty. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidPatientID {
            get {
                return ResourceManager.GetString("ExceptionInvalidPatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotation value must be 0, 90, 180 or 270. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidRotationValue {
            get {
                return ResourceManager.GetString("ExceptionInvalidRotationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is an invalid standard path item. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidStandardPathItem {
            get {
                return ResourceManager.GetString("ExceptionInvalidStandardPathItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stride improperly calculated (correct stride = {0}, calculated stride = {1}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidStride {
            get {
                return ResourceManager.GetString("ExceptionInvalidStride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The layout of the physical workspace is either non-rectangular or has not been set. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionLayoutIsNotRectangular {
            get {
                return ResourceManager.GetString("ExceptionLayoutIsNotRectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Linear Luts have no settable data. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionLinearLutDataCannotBeSet {
            get {
                return ResourceManager.GetString("ExceptionLinearLutDataCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LUT index out of range (index = {0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionLUTIndexOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionLUTIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output range of previous LUT does not match input range of current LUT. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionLUTInputOutputRange {
            get {
                return ResourceManager.GetString("ExceptionLUTInputOutputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output range of last LUT is not 8 bits. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionLUTLastOutputRange {
            get {
                return ResourceManager.GetString("ExceptionLUTLastOutputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum input value greater than or equal to maximum input value. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionLUTMinGreaterThanEqualToMax {
            get {
                return ResourceManager.GetString("ExceptionLUTMinGreaterThanEqualToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot generate composite LUT because no LUTs have been added yet. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionLUTNotAdded {
            get {
                return ResourceManager.GetString("ExceptionLUTNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The maximum output value is not settable. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionMaximumOutputValueIsNotSettable {
            get {
                return ResourceManager.GetString("ExceptionMaximumOutputValueIsNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The minimum output value is not settable. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionMinimumOutputValueIsNotSettable {
            get {
                return ResourceManager.GetString("ExceptionMinimumOutputValueIsNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The minimum and maximum input values have not been set. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionMinMaxInputValuesNotSet {
            get {
                return ResourceManager.GetString("ExceptionMinMaxInputValuesNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must override SetMemento in order to restore state from a previous call to CreateMemento. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionMustOverrideSetMemento {
            get {
                return ResourceManager.GetString("ExceptionMustOverrideSetMemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is the ImageBox to which this Tile belongs supposed to be empty? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionNoDisplaySetAssociatedWithImageBoxTile {
            get {
                return ResourceManager.GetString("ExceptionNoDisplaySetAssociatedWithImageBoxTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is the tile supposed to be empty? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionNoPresentationImageAssociatedWithTile {
            get {
                return ResourceManager.GetString("ExceptionNoPresentationImageAssociatedWithTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No SOPs exist in this series.  SeriesDescription cannot be determined. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionNoSopsExistInSeries {
            get {
                return ResourceManager.GetString("ExceptionNoSopsExistInSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object must be of Type Single. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionObjectMustBeSingleType {
            get {
                return ResourceManager.GetString("ExceptionObjectMustBeSingleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sop Instance validation failed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionSopInstanceValidationFailed {
            get {
                return ResourceManager.GetString("ExceptionSopInstanceValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For undo support, your StatefulGraphic subclass must implement IMemorable. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionStatefulGraphicMustBeIMemorable {
            get {
                return ResourceManager.GetString("ExceptionStatefulGraphicMustBeIMemorable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} [C:{1:F2}% B:{2:F2}%] benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatAdjustableDataLutDescription {
            get {
                return ResourceManager.GetString("FormatAdjustableDataLutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:F1}° benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatAngleDegrees {
            get {
                return ResourceManager.GetString("FormatAngleDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}: {1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatAnnotationItem {
            get {
                return ResourceManager.GetString("FormatAnnotationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area: {0:F1} pixels benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatAreaPixels {
            get {
                return ResourceManager.GetString("FormatAreaPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area: {0:F3} cm² benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatAreaSquareCm {
            get {
                return ResourceManager.GetString("FormatAreaSquareCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area: {0:F1} mm² benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatAreaSquareMm {
            get {
                return ResourceManager.GetString("FormatAreaSquareMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay Plane ({0} #{1}, Fr #{2}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDefaultMultiFrameOverlayGraphicName {
            get {
                return ResourceManager.GetString("FormatDefaultMultiFrameOverlayGraphicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay Plane ({0} #{1}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDefaultSingleFrameOverlayGraphicName {
            get {
                return ResourceManager.GetString("FormatDefaultSingleFrameOverlayGraphicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W:{0:0.#} L:{1:0.#} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDescriptionBasicLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionBasicLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W:{0:0.#} L:{1:0.#} (Identity) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDescriptionIdentityVoiLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionIdentityVoiLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W:{0:0.#} L:{1:0.#} (Min/Max) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDescriptionMinMaxCalculatedLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionMinMaxCalculatedLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] All Images benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDescriptionModalityDisplaySet {
            get {
                return ResourceManager.GetString("FormatDescriptionModalityDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slope: {0:F2} Int.: {1:F2} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDescriptionModalityLutLinear {
            get {
                return ResourceManager.GetString("FormatDescriptionModalityLutLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W:{0:0.#} L:{1:0.#} ({2}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDescriptionNamedLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionNamedLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W:{0:0.#} L:{1:0.#} ({2}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDescriptionPresentationStateLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionPresentationStateLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reason: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatExceptionReason {
            get {
                return ResourceManager.GetString("FormatExceptionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:F2} cm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatLengthCm {
            get {
                return ResourceManager.GetString("FormatLengthCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:F1} mm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatLengthMm {
            get {
                return ResourceManager.GetString("FormatLengthMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0:F1} pixels benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatLengthPixels {
            get {
                return ResourceManager.GetString("FormatLengthPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mean: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMean {
            get {
                return ResourceManager.GetString("FormatMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} : {1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMouseButtonShortcutDescription {
            get {
                return ResourceManager.GetString("FormatMouseButtonShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The mouse tool does not have a shortcut assignment ({0}).  The tool cannot be activated. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMouseToolHasNoAssignment {
            get {
                return ResourceManager.GetString("FormatMouseToolHasNoAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The mouse tool has an invalid shortcut assignment ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMouseToolInvalidAssignment {
            get {
                return ResourceManager.GetString("FormatMouseToolInvalidAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wheel : {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMouseWheelShortcutDescription {
            get {
                return ResourceManager.GetString("FormatMouseWheelShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] All Images benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatNameModalityDisplaySet {
            get {
                return ResourceManager.GetString("FormatNameModalityDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reason: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatReason {
            get {
                return ResourceManager.GetString("FormatReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Std Dev: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatStdDev {
            get {
                return ResourceManager.GetString("FormatStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelError {
            get {
                return ResourceManager.GetString("LabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelPresentationVoiDataLut {
            get {
                return ResourceManager.GetString("LabelPresentationVoiDataLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelPresentationVoiLinearLut {
            get {
                return ResourceManager.GetString("LabelPresentationVoiLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1/cm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnits1cm {
            get {
                return ResourceManager.GetString("LabelUnits1cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bq/ml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsBqml {
            get {
                return ResourceManager.GetString("LabelUnitsBqml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cm² benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsCm2 {
            get {
                return ResourceManager.GetString("LabelUnitsCm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cm²/ml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsCm2ml {
            get {
                return ResourceManager.GetString("LabelUnitsCm2ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   counts benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsCnts {
            get {
                return ResourceManager.GetString("LabelUnitsCnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   counts/s benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsCps {
            get {
                return ResourceManager.GetString("LabelUnitsCps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   g/ml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsGml {
            get {
                return ResourceManager.GetString("LabelUnitsGml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsHU {
            get {
                return ResourceManager.GetString("LabelUnitsHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mg/min/ml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsMgminml {
            get {
                return ResourceManager.GetString("LabelUnitsMgminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ml/g benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsMlg {
            get {
                return ResourceManager.GetString("LabelUnitsMlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ml/min/g benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsMlming {
            get {
                return ResourceManager.GetString("LabelUnitsMlming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ml/min/ml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsMlminml {
            get {
                return ResourceManager.GetString("LabelUnitsMlminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ml/ml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsMlml {
            get {
                return ResourceManager.GetString("LabelUnitsMlml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mm² benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsMm2 {
            get {
                return ResourceManager.GetString("LabelUnitsMm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1/1000 OD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsOD {
            get {
                return ResourceManager.GetString("LabelUnitsOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   % benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsPcnt {
            get {
                return ResourceManager.GetString("LabelUnitsPcnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pixels benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsPixels {
            get {
                return ResourceManager.GetString("LabelUnitsPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   prop. to counts benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsPropcnts {
            get {
                return ResourceManager.GetString("LabelUnitsPropcnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   prop. to counts/s benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsPropcps {
            get {
                return ResourceManager.GetString("LabelUnitsPropcps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   σ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsStddev {
            get {
                return ResourceManager.GetString("LabelUnitsStddev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   µmol/min/ml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsUmolminml {
            get {
                return ResourceManager.GetString("LabelUnitsUmolminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   µmol/ml benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsUmolml {
            get {
                return ResourceManager.GetString("LabelUnitsUmolml", resourceCulture);
            }
        }
        
        /// <summary>
        ///    benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnitsUnspecified {
            get {
                return ResourceManager.GetString("LabelUnitsUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnknown {
            get {
                return ResourceManager.GetString("LabelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelUnknownServer {
            get {
                return ResourceManager.GetString("LabelUnknownServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Vertex benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuDeleteVertex {
            get {
                return ResourceManager.GetString("MenuDeleteVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuEditText {
            get {
                return ResourceManager.GetString("MenuEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Vertex benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuInsertVertex {
            get {
                return ResourceManager.GetString("MenuInsertVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Analysis benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuShowAnalysis {
            get {
                return ResourceManager.GetString("MenuShowAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please contact your PACS administrator for assistance. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageContactPacsAdmin {
            get {
                return ResourceManager.GetString("MessageContactPacsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occured while attempting to clone a display set.  Please check the log for more details. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageErrorCloningDisplaySet {
            get {
                return ResourceManager.GetString("MessageErrorCloningDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occured while attempting to clone an image.  Please check the log for more details. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageErrorCloningPresentationImage {
            get {
                return ResourceManager.GetString("MessageErrorCloningPresentationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One or more overlays
        ///cannot be displayed.
        ///Use image with caution. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageErrorDisplayingOverlays {
            get {
                return ResourceManager.GetString("MessageErrorDisplayingOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unrecoverable error occurred while attempting to load the text overlay.  Please see the log for details. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageErrorLoadingAnnotationLayout {
            get {
                return ResourceManager.GetString("MessageErrorLoadingAnnotationLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while trying to add graphics from the image header.  Some or all of them will not appear. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFailedToApplyDicomHeaderGraphics {
            get {
                return ResourceManager.GetString("MessageFailedToApplyDicomHeaderGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClearCanvas was only able to load {0} of the {1} images you requested. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatLoadStudyIncomplete {
            get {
                return ResourceManager.GetString("MessageFormatLoadStudyIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opening {0} of {1} images benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatOpeningImages {
            get {
                return ResourceManager.GetString("MessageFormatOpeningImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///{1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatStudyNotLoadable {
            get {
                return ResourceManager.GetString("MessageFormatStudyNotLoadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} studies were only partially loaded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatXStudiesIncomplete {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} studies are in use. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatXStudiesInUse {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} studies are nearline. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatXStudiesNearline {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} studies were not found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatXStudiesNotFound {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} studies could not be loaded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatXStudiesNotLoaded {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} studies are offline. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatXStudiesOffline {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study is on a non-streaming server and must be retrieved and reopened. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageInfoNoStudyLoader {
            get {
                return ResourceManager.GetString("MessageInfoNoStudyLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study could not be loaded.  Please contact your PACS administrator. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageInfoStudyCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("MessageInfoStudyCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study is in use.  Please close the current study, wait a few minutes, then try loading the study again. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageInfoStudyInUse {
            get {
                return ResourceManager.GetString("MessageInfoStudyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study is nearline.  If your PACS is a ClearCanvas ImageServer, please try opening the study manually, then wait a few minutes before trying again.
        ///Alternately, the study can be brought back online by a PACS administrator. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageInfoStudyNearline {
            get {
                return ResourceManager.GetString("MessageInfoStudyNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study is offline and must be brought back online by a PACS administrator. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageInfoStudyOffline {
            get {
                return ResourceManager.GetString("MessageInfoStudyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred while deserializing the key object selection document. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageKeyObjectDeserializeFailure {
            get {
                return ResourceManager.GetString("MessageKeyObjectDeserializeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following failures occurred while loading studies: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageLoadMultipleStudiesFailurePrefix {
            get {
                return ResourceManager.GetString("MessageLoadMultipleStudiesFailurePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClearCanvas was unable to load any of the images you requested. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageLoadStudyCompleteFailure {
            get {
                return ResourceManager.GetString("MessageLoadStudyCompleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study is being processed by the server and cannot be loaded at this time.  Please try again later. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageLoadStudyFailedInUse {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study is currently being restored from archive and cannot be loaded at this time.  Please try again later. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageLoadStudyFailedNearline {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study is nearline and cannot be restored at this time.  Please contact your PACS administrator to restore the study. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageLoadStudyFailedNearlineNoRestore {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedNearlineNoRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study could not be found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageLoadStudyFailedNotFound {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study cannot be loaded because it is offline. Please contact your PACS administrator to restore the study. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageLoadStudyFailedOffline {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No renderer plugins exist; defaulting to GDI renderer. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageNoRendererPluginsExist {
            get {
                return ResourceManager.GetString("MessageNoRendererPluginsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No images could be loaded for display. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageNoVisibleDisplaySets {
            get {
                return ResourceManager.GetString("MessageNoVisibleDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One study was only partially loaded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageOneStudyIncomplete {
            get {
                return ResourceManager.GetString("MessageOneStudyIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One study is in use. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageOneStudyInUse {
            get {
                return ResourceManager.GetString("MessageOneStudyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One study is nearline. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageOneStudyNearline {
            get {
                return ResourceManager.GetString("MessageOneStudyNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One study was not found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageOneStudyNotFound {
            get {
                return ResourceManager.GetString("MessageOneStudyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One study could not be loaded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageOneStudyNotLoaded {
            get {
                return ResourceManager.GetString("MessageOneStudyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One study is offline. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageOneStudyOffline {
            get {
                return ResourceManager.GetString("MessageOneStudyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occured while attempting to load a presentation state. The presentation state may not have been loaded in its entirety. Please check the log for more details. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePresentationStateApplicationFailure {
            get {
                return ResourceManager.GetString("MessagePresentationStateApplicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred while deserializing the image presentation state. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePresentationStateDeserializeFailure {
            get {
                return ResourceManager.GetString("MessagePresentationStateDeserializeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occured while attempting to read a presentation state file. Please check the log for more details. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePresentationStateReadFailure {
            get {
                return ResourceManager.GetString("MessagePresentationStateReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The referenced key image was found, but does not contain the specified frame. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageReferencedKeyImageFrameNotFound {
            get {
                return ResourceManager.GetString("MessageReferencedKeyImageFrameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The referenced key image could not be displayed because it is not part of the loaded study. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageReferencedKeyImageFromOtherStudy {
            get {
                return ResourceManager.GetString("MessageReferencedKeyImageFromOtherStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred in the rendering pipeline. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageRenderingPipelineFailure {
            get {
                return ResourceManager.GetString("MessageRenderingPipelineFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred while analyzing the Roi.
        ///Please check the log for more details. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageRoiAnalysisError {
            get {
                return ResourceManager.GetString("MessageRoiAnalysisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported Image Type: {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUnsupportedImageType {
            get {
                return ResourceManager.GetString("MessageUnsupportedImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected images are of an unsupported type. MPR only supports DICOM image SOPs. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceAreNotSupported {
            get {
                return ResourceManager.GetString("MessageVolumeSourceAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each frame in the source dataset must be of the same anatomical laterality. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceInconsistentImageLaterality {
            get {
                return ResourceManager.GetString("MessageVolumeSourceInconsistentImageLaterality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each frame in the source dataset must be in the same pixel units. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceInconsistentRescaleUnits {
            get {
                return ResourceManager.GetString("MessageVolumeSourceInconsistentRescaleUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected images have a gantry slew. MPR only supports gantry tilts. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMayBotBeGantrySlewed {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMayBotBeGantrySlewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected images have an anisotropic pixel aspect ratio. MPR only supports 1:1 isotropic aspect ratios. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMayNotHaveAnisotropicPixels {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMayNotHaveAnisotropicPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source dataset must contain at least three frames. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMinimumThreeImages {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMinimumThreeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPR only supports 16-bit greyscale images. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustBe16BitGreyscale {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBe16BitGreyscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The selected images must be calibrated. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustBeCalibrated {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeCalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inconsistent spacing between images. MPR requires evenly spaced images. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustBeEvenlySpacedForMpr {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeEvenlySpacedForMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each frame in the source dataset must have the same image orientation (Patient). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustBeSameImageOrientationPatient {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeSameImageOrientationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each frame in the source dataset must have the same frame of reference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustBeSingleFrameOfReference {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeSingleFrameOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each frame in the source dataset must be from the same series. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustBeSingleSeries {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeSingleSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each frame in the source dataset must be from the same study. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustBeSingleStudy {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeSingleStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two images are at same patient location. MPR requires evenly spaced images. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustBeUniquelyLocatedForMpr {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeUniquelyLocatedForMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each frame in the source dataset must have a defined image orientation (Patient). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustDefineImageOrientationPatient {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustDefineImageOrientationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Each frame in the source dataset must specify a frame of reference. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceMustSpecifyFrameOfReference {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustSpecifyFrameOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected exception was encountered while creating the volume. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageVolumeSourceUnexpectedException {
            get {
                return ResourceManager.GetString("MessageVolumeSourceUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visible Display Set benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NamePrefetchingStrategyVisibleDisplaySet {
            get {
                return ResourceManager.GetString("NamePrefetchingStrategyVisibleDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SeparatorPatientDescription {
            get {
                return ResourceManager.GetString("SeparatorPatientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   :: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SeparatorPatientsLoaded {
            get {
                return ResourceManager.GetString("SeparatorPatientsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   N/A benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StringNotApplicable {
            get {
                return ResourceManager.GetString("StringNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --- benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StringNoValue {
            get {
                return ResourceManager.GetString("StringNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key Images benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatKeyImageDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatKeyImageDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Echo #{0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatMREchoDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatMREchoDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiframe #{0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatMultiframeDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatMultiframeDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stack {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatMultiframeStackDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatMultiframeStackDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image/Frame#: {0}/{1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatSingleFrameDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatSingleFrameDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image #{0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatSingleImageDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatSingleImageDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} (Image# {1}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatSingleImageDisplaySetWithLateralityViewPosition {
            get {
                return ResourceManager.GetString("SuffixFormatSingleImageDisplaySetWithLateralityViewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Series/Image/Frame: {0}/{1}/{2} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatSingleReferencedFrameDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatSingleReferencedFrameDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Series/Image#: {0}/{1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatSingleReferencedImageDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatSingleReferencedImageDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} (Series/Image#: {1}/{2}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixFormatSingleReferencedImageDisplaySetWithLateralityViewPosition {
            get {
                return ResourceManager.GetString("SuffixFormatSingleReferencedImageDisplaySetWithLateralityViewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single images benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SuffixSingleImagesDisplaySet {
            get {
                return ResourceManager.GetString("SuffixSingleImagesDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ValueNil {
            get {
                return ResourceManager.GetString("ValueNil", resourceCulture);
            }
        }
    }
}
