//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Layout.Basic {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Layout.Basic.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Explode Tile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandExplodeTile {
            get {
                return ResourceManager.GetString("CommandExplodeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout image boxes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandLayoutImageBoxes {
            get {
                return ResourceManager.GetString("CommandLayoutImageBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout tiles benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandLayoutTiles {
            get {
                return ResourceManager.GetString("CommandLayoutTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Survey/Explode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandSurveyExplode {
            get {
                return ResourceManager.GetString("CommandSurveyExplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (List of Display Sets) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DisplaySets {
            get {
                return ResourceManager.GetString("DisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified image is not currently loaded (SopInstanceUID={0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionImageNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionImageNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified series is not currently loaded (SeriesInstanceUID={0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionSeriesNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionSeriesNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified study is not currently loaded (StudyInstanceUID={0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionStudyNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionStudyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in use benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create single image display sets benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelCreateSingleImageDisplaySets {
            get {
                return ResourceManager.GetString("LabelCreateSingleImageDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Default) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study is {0}. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelFormatStudyUnavailable {
            get {
                return ResourceManager.GetString("LabelFormatStudyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading Priors ... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelLoadingPriors {
            get {
                return ResourceManager.GetString("LabelLoadingPriors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split multi-echo series benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelSplitEchos {
            get {
                return ResourceManager.GetString("LabelSplitEchos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split mixed mult-frame series benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelSplitMultiframes {
            get {
                return ResourceManager.GetString("LabelSplitMultiframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The study could not be loaded. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelStudyCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("LabelStudyCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Survey/Explode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuExplodeImageBox {
            get {
                return ResourceManager.GetString("MenuExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout Manager benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuLayoutManager {
            get {
                return ResourceManager.GetString("MenuLayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Display Set benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuNextDisplaySet {
            get {
                return ResourceManager.GetString("MenuNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Display Set benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuPreviousDisplaySet {
            get {
                return ResourceManager.GetString("MenuPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide &amp;Colour Bar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuShowHideColorBar {
            get {
                return ResourceManager.GetString("MenuShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide DICOM Overlay(s) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Scale Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Shutter Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Text Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuShowHideTextOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuStandard {
            get {
                return ResourceManager.GetString("MenuStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following errors occurred while loading prior studies: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageLoadPriorsErrorPrefix {
            get {
                return ResourceManager.GetString("MessageLoadPriorsErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The search for prior studies did not complete successfully because at least one of your default servers was unreachable.
        ///Although some priors may be available, please be aware that you may be working with an incomplete patient history.
        ///
        ///PLEASE NOTE that you will NOT be notified of this problem again for as long as this problem persists. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePriorsIncomplete {
            get {
                return ResourceManager.GetString("MessagePriorsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The search for prior studies has failed.  Try reopening the study or select a different default server.
        ///
        ///PLEASE NOTE that you will NOT be notified of this problem again for as long as this problem persists. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageSearchForPriorsFailed {
            get {
                return ResourceManager.GetString("MessageSearchForPriorsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Bar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameColourBarOverlay {
            get {
                return ResourceManager.GetString("NameColourBarOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICOM benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameDicomOverlay {
            get {
                return ResourceManager.GetString("NameDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameScaleOverlay {
            get {
                return ResourceManager.GetString("NameScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shutter benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameShutterOverlay {
            get {
                return ResourceManager.GetString("NameShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NameTextOverlay {
            get {
                return ResourceManager.GetString("NameTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   nearline benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Nearline {
            get {
                return ResourceManager.GetString("Nearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   offline benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Sets benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleDisplaySetCreationConfiguration {
            get {
                return ResourceManager.GetString("TitleDisplaySetCreationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleLayoutConfiguration {
            get {
                return ResourceManager.GetString("TitleLayoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout Manager benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleLayoutManager {
            get {
                return ResourceManager.GetString("TitleLayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Layout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarChangeLayout {
            get {
                return ResourceManager.GetString("ToolbarChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colour Bar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarColorBar {
            get {
                return ResourceManager.GetString("ToolbarColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DICOM Overlay(s) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarDicomOverlay {
            get {
                return ResourceManager.GetString("ToolbarDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Survey/Explode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarExplodeImageBox {
            get {
                return ResourceManager.GetString("ToolbarExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Box Layout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarLayoutBoxesChooser {
            get {
                return ResourceManager.GetString("ToolbarLayoutBoxesChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tile Layout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarLayoutTilesChooser {
            get {
                return ResourceManager.GetString("ToolbarLayoutTilesChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Display Set benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarNextDisplaySet {
            get {
                return ResourceManager.GetString("ToolbarNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Display Set benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarPreviousDisplaySet {
            get {
                return ResourceManager.GetString("ToolbarPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarScaleOverlay {
            get {
                return ResourceManager.GetString("ToolbarScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Overlays benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarShowHideOverlays {
            get {
                return ResourceManager.GetString("ToolbarShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shutter Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarShutterOverlay {
            get {
                return ResourceManager.GetString("ToolbarShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarTextOverlay {
            get {
                return ResourceManager.GetString("ToolbarTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Layout benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipChangeLayout {
            get {
                return ResourceManager.GetString("TooltipChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Survey/Explode benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipExplodeImageBox {
            get {
                return ResourceManager.GetString("TooltipExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide all overlays benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipHideOverlays {
            get {
                return ResourceManager.GetString("TooltipHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Display Set benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipNextDisplaySet {
            get {
                return ResourceManager.GetString("TooltipNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Display Set benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipPreviousDisplaySet {
            get {
                return ResourceManager.GetString("TooltipPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Colour Bar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipShowHideColorBar {
            get {
                return ResourceManager.GetString("TooltipShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide DICOM Overlay(s) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Overlays benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipShowHideOverlays {
            get {
                return ResourceManager.GetString("TooltipShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Scale Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Shutter Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Text Overlay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipShowHideTextOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show selected overlays benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipShowOverlays {
            get {
                return ResourceManager.GetString("TooltipShowOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   unavailable benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
    }
}
