//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Volume.Mpr {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Volume.Mpr.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Move MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandMprMove {
            get {
                return ResourceManager.GetString("CommandMprMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandMprReset {
            get {
                return ResourceManager.GetString("CommandMprReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reslice MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandMprReslice {
            get {
                return ResourceManager.GetString("CommandMprReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to load the selected images in MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionMprLoadFailure {
            get {
                return ResourceManager.GetString("ExceptionMprLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPR ({0}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMprDisplaySetName {
            get {
                return ResourceManager.GetString("FormatMprDisplaySetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPR {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMprWorkspaceTitle {
            get {
                return ResourceManager.GetString("FormatMprWorkspaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (X{0:f0}° x Y{1:f0}° x Z{2:f0}°) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatSliceCustom {
            get {
                return ResourceManager.GetString("FormatSliceCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identity benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatSliceIdentity {
            get {
                return ResourceManager.GetString("FormatSliceIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OrthoX benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatSliceOrthogonalX {
            get {
                return ResourceManager.GetString("FormatSliceOrthogonalX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OrthoY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatSliceOrthogonalY {
            get {
                return ResourceManager.GetString("FormatSliceOrthogonalY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} - {1} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatVolumeLabel {
            get {
                return ResourceManager.GetString("FormatVolumeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {2} ({0} - {1}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatVolumeLabelWithSeries {
            get {
                return ResourceManager.GetString("FormatVolumeLabelWithSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Debug benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuMpr {
            get {
                return ResourceManager.GetString("MenuMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Selection with &amp;MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuOpenSelectionWithMpr {
            get {
                return ResourceManager.GetString("MenuOpenSelectionWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open with &amp;MPR... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuOpenWithMpr {
            get {
                return ResourceManager.GetString("MenuOpenWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Reset MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuResetAll {
            get {
                return ResourceManager.GetString("MenuResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reslice MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuReslice {
            get {
                return ResourceManager.GetString("MenuReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reslice {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuResliceFor {
            get {
                return ResourceManager.GetString("MenuResliceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Volume benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuVolume {
            get {
                return ResourceManager.GetString("MenuVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Building MPR Volume... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageBuildingMprVolume {
            get {
                return ResourceManager.GetString("MessageBuildingMprVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Building MPR Volume (Frame {1} of {2})... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageBuildingMprVolumeProgress {
            get {
                return ResourceManager.GetString("MessageBuildingMprVolumeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageDone {
            get {
                return ResourceManager.GetString("MessageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing MPR... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageInitializingMpr {
            get {
                return ResourceManager.GetString("MessageInitializingMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Performing MPR Workspace Layout... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePerformingMprWorkspaceLayout {
            get {
                return ResourceManager.GetString("MessagePerformingMprWorkspaceLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is not a valid, supported DICOM image SOP instance. {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUnsupportedDicomImageSop {
            get {
                return ResourceManager.GetString("MessageUnsupportedDicomImageSop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slice spacing must be greater than or equal to 0.5 and less than or equal to 10. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageValidateSliceSpacing {
            get {
                return ResourceManager.GetString("MessageValidateSliceSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mpr {
            get {
                return ResourceManager.GetString("Mpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 Plane benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ThreePlane {
            get {
                return ResourceManager.GetString("ThreePlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarMpr {
            get {
                return ResourceManager.GetString("ToolbarMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Selection with MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarOpenSelectionWithMpr {
            get {
                return ResourceManager.GetString("ToolbarOpenSelectionWithMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarResetAll {
            get {
                return ResourceManager.GetString("ToolbarResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reslice MPR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarReslice {
            get {
                return ResourceManager.GetString("ToolbarReslice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reslice {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarResliceFor {
            get {
                return ResourceManager.GetString("ToolbarResliceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resets all MPR slice views benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipResetAll {
            get {
                return ResourceManager.GetString("TooltipResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   :: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string VolumeLabelSeparator {
            get {
                return ResourceManager.GetString("VolumeLabelSeparator", resourceCulture);
            }
        }
    }
}
