//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.StudyFinders.Remote {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.StudyFinders.Remote.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Multiple wildcard queries cannot be performed on the ModalitiesInStudy tag. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionModalitiesInStudyCannotPerformMultipleWildcardQueries {
            get {
                return ResourceManager.GetString("ExceptionModalitiesInStudyCannotPerformMultipleWildcardQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Association rejected ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatAssociationRejected {
            get {
                return ResourceManager.GetString("MessageFormatAssociationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection failed ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatConnectionFailed {
            get {
                return ResourceManager.GetString("MessageFormatConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The connection timeout expired ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatConnectTimeoutExpired {
            get {
                return ResourceManager.GetString("MessageFormatConnectTimeoutExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The query operation failed ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatQueryOperationFailed {
            get {
                return ResourceManager.GetString("MessageFormatQueryOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The remote server cancelled the query ({0}). benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatRemoteServerCancelledFind {
            get {
                return ResourceManager.GetString("MessageFormatRemoteServerCancelledFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected message was received; aborted association. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUnexpectedMessage {
            get {
                return ResourceManager.GetString("MessageUnexpectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected network error has occurred. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUnexpectedNetworkError {
            get {
                return ResourceManager.GetString("MessageUnexpectedNetworkError", resourceCulture);
            }
        }
    }
}
