//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Desktop.ExtensionBrowser {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Desktop.ExtensionBrowser.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Extension Points ({0}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatExtensionPointsDisplayName {
            get {
                return ResourceManager.GetString("FormatExtensionPointsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension Browser benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuExtensionBrowser {
            get {
                return ResourceManager.GetString("MenuExtensionBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension Browser benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleExtensionBrowser {
            get {
                return ResourceManager.GetString("TitleExtensionBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extensions ({0}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TreeExtensionPointViewExtensionsNode {
            get {
                return ResourceManager.GetString("TreeExtensionPointViewExtensionsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension Points ({0}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TreeExtensionPointViewRootNode {
            get {
                return ResourceManager.GetString("TreeExtensionPointViewRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension Points ({0}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TreePluginViewExtensionPointsNode {
            get {
                return ResourceManager.GetString("TreePluginViewExtensionPointsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension Points declared in plugin {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TreePluginViewExtensionPointsNodeDetails {
            get {
                return ResourceManager.GetString("TreePluginViewExtensionPointsNodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extensions ({0}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TreePluginViewExtensionsNode {
            get {
                return ResourceManager.GetString("TreePluginViewExtensionsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extensions declared in plugin {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TreePluginViewExtensionsNodeDetails {
            get {
                return ResourceManager.GetString("TreePluginViewExtensionsNodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plugins ({0}) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TreePluginViewRootNode {
            get {
                return ResourceManager.GetString("TreePluginViewRootNode", resourceCulture);
            }
        }
    }
}
