//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Explorer.Local {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Explorer.Local.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to import the selected items because the local services are not running.
        ///Please ensure the &apos;{0}&apos; is running or contact your system administrator for assistance. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMessageImportWorkItemServiceNotRunning {
            get {
                return ResourceManager.GetString("FormatMessageImportWorkItemServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ImportDicomFiles {
            get {
                return ResourceManager.GetString("ImportDicomFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Activity Monitor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LinkOpenActivityMonitor {
            get {
                return ResourceManager.GetString("LinkOpenActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuOpenFiles {
            get {
                return ResourceManager.GetString("MenuOpenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to initiate an import of the selected items. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFailedToImportSelection {
            get {
                return ResourceManager.GetString("MessageFailedToImportSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified file could not be found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFileNotFound {
            get {
                return ResourceManager.GetString("MessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} images failed to load. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatImagesFailedToLoad {
            get {
                return ResourceManager.GetString("MessageFormatImagesFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Importing files from {0} location. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatImportingFiles {
            get {
                return ResourceManager.GetString("MessageFormatImportingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Importing files from {0} locations. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageFormatImportingFilesPlural {
            get {
                return ResourceManager.GetString("MessageFormatImportingFilesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified path does not contain any files. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageNoFilesSelected {
            get {
                return ResourceManager.GetString("MessageNoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to open images in the viewer. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePermissionToOpenFilesDenied {
            get {
                return ResourceManager.GetString("MessagePermissionToOpenFilesDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to open images. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUnableToOpenImages {
            get {
                return ResourceManager.GetString("MessageUnableToOpenImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Computer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MyComputer {
            get {
                return ResourceManager.GetString("MyComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Dicom Files benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string OpenDicomFilesVerbose {
            get {
                return ResourceManager.GetString("OpenDicomFilesVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import DICOM files from the local file system benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipImportDicomFiles {
            get {
                return ResourceManager.GetString("TooltipImportDicomFiles", resourceCulture);
            }
        }
    }
}
