//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.View.WinForms {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.View.WinForms.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The AE Title of the local DICOM server is &apos;{0}&apos; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ActivityMonitorAeTitleToolTip {
            get {
                return ResourceManager.GetString("ActivityMonitorAeTitleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open folder {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ActivityMonitorFileStoreToolTip {
            get {
                return ResourceManager.GetString("ActivityMonitorFileStoreToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The host/port on which the local DICOM server is listening is {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ActivityMonitorHostPortToolTip {
            get {
                return ResourceManager.GetString("ActivityMonitorHostPortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stack benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CommandNameStackImageScroller {
            get {
                return ResourceManager.GetString("CommandNameStackImageScroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PresentationImage not associated with an IRenderer. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionPresentationImageNotAssociatedWithARenderer {
            get {
                return ResourceManager.GetString("ExceptionPresentationImageNotAssociatedWithARenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TileControl is not associated with a tile. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionTileControlNoAssociatedTile {
            get {
                return ResourceManager.GetString("ExceptionTileControlNoAssociatedTile", resourceCulture);
            }
        }
    }
}
