//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:2.0.50727.5485
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Desktop {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Desktop.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertFilterAll {
            get {
                return ResourceManager.GetString("AlertFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Errors and Warnings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertFilterErrorsAndWarnings {
            get {
                return ResourceManager.GetString("AlertFilterErrorsAndWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Errors only benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AlertFilterErrorsOnly {
            get {
                return ResourceManager.GetString("AlertFilterErrorsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ColumnLevel {
            get {
                return ResourceManager.GetString("ColumnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ColumnMessage {
            get {
                return ResourceManager.GetString("ColumnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ColumnTime {
            get {
                return ResourceManager.GetString("ColumnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Workspace benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ColumnWorkspace {
            get {
                return ResourceManager.GetString("ColumnWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Theme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionDefaultTheme {
            get {
                return ResourceManager.GetString("DescriptionDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configures global exception handling behaviour. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionExceptionHandlerSettings {
            get {
                return ResourceManager.GetString("DescriptionExceptionHandlerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allows configuration of display format of common items such as dates, times, etc. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DescriptionFormatSettings {
            get {
                return ResourceManager.GetString("DescriptionFormatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The event {0} does not exist for class {1}. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionActionBuilderEventDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderEventDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The method {0} does not exist for class {1}, or it does not have the correct signature. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionActionBuilderMethodDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderMethodDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The property {0} does not exist for class {1}, or it does not have the correct return type. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionActionBuilderPropertyDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderPropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The property {0} on class {1} does not have a public get method. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionActionBuilderPropertyDoesNotHavePublicGetMethod {
            get {
                return ResourceManager.GetString("ExceptionActionBuilderPropertyDoesNotHavePublicGetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot set the active workspace to null. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionActiveWorkspaceCannotBeNull {
            get {
                return ResourceManager.GetString("ExceptionActiveWorkspaceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An AssociateViewAttribute must be specified for the input Type in order to create the Associated View. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionAssociateViewAttributeNotSpecified {
            get {
                return ResourceManager.GetString("ExceptionAssociateViewAttributeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot load exception dialog settings - defaulting to detailed view benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionCannotLoadExceptionDialogSetting {
            get {
                return ResourceManager.GetString("ExceptionCannotLoadExceptionDialogSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot set pane after container has been started. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionCannotSetPaneAfterContainerStarted {
            get {
                return ResourceManager.GetString("ExceptionCannotSetPaneAfterContainerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Component has already been started. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionComponentAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionComponentAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Component was never started, or has already been stopped. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionComponentNeverStarted {
            get {
                return ResourceManager.GetString("ExceptionComponentNeverStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Container has already been started benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionContainerAlreadyStarted {
            get {
                return ResourceManager.GetString("ExceptionContainerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Container was never started, or has already been stopped. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionContainerNeverStarted {
            get {
                return ResourceManager.GetString("ExceptionContainerNeverStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The main desktop view has not been created. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionDesktopViewNotCreated {
            get {
                return ResourceManager.GetString("ExceptionDesktopViewNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occured while attempting to save changes to this item benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionFailedToSave {
            get {
                return ResourceManager.GetString("ExceptionFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid action path.  Path must have 2 or more segments. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionInvalidActionPath {
            get {
                return ResourceManager.GetString("ExceptionInvalidActionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collection already contains this object benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionObjectAlreadyInCollection {
            get {
                return ResourceManager.GetString("ExceptionObjectAlreadyInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An object with the name {0} already exists benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionObjectWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionObjectWithNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference property must be of same type as validating property. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionReferencePropertyMustBeOfSameType {
            get {
                return ResourceManager.GetString("ExceptionReferencePropertyMustBeOfSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference value must be of same type as validating property. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionReferenceValueMustBeOfSameType {
            get {
                return ResourceManager.GetString("ExceptionReferenceValueMustBeOfSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Component cannot exit because it is not at the top of the component stack. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionStackComponentCannotExit {
            get {
                return ResourceManager.GetString("ExceptionStackComponentCannotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot pop - component stack is empty. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionStackComponentCannotPop {
            get {
                return ResourceManager.GetString("ExceptionStackComponentCannotPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This column must be added to a table to determine its percentage width. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionTableColumnMustBeAddedToDetermineWidth {
            get {
                return ResourceManager.GetString("ExceptionTableColumnMustBeAddedToDetermineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Table item not found in collection. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionTableItemNotFoundInCollection {
            get {
                return ResourceManager.GetString("ExceptionTableItemNotFoundInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application configuration upgrades are performed by the LocalFileSettingsProvider included in the .NET framework. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExceptionUpgradeNotSupported {
            get {
                return ResourceManager.GetString("ExceptionUpgradeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} attribute cannot be applied to property of type {1}. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatAttributeCannotBeAppliedToPropertyType {
            get {
                return ResourceManager.GetString("FormatAttributeCannotBeAppliedToPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} days from now benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDateInFutureDays {
            get {
                return ResourceManager.GetString("FormatDateInFutureDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} days ago benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDateInPastDays {
            get {
                return ResourceManager.GetString("FormatDateInPastDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} [{1}] benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatDesktopWindowTitle {
            get {
                return ResourceManager.GetString("FormatDesktopWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More than {0} characters required benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMoreThanXCharactersRequired {
            get {
                return ResourceManager.GetString("FormatMoreThanXCharactersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must be greater than {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMustBeGreaterThan {
            get {
                return ResourceManager.GetString("FormatMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must be greater than or equal to {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FormatMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must be less than {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMustBeLessThan {
            get {
                return ResourceManager.GetString("FormatMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must be less than or equal to {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FormatMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Between {0} and {1} characters required benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatRangeCharactersRequired {
            get {
                return ResourceManager.GetString("FormatRangeCharactersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatTimeToday {
            get {
                return ResourceManager.GetString("FormatTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tomorrow {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatTimeTomorrow {
            get {
                return ResourceManager.GetString("FormatTimeTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yesterday {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatTimeYesterday {
            get {
                return ResourceManager.GetString("FormatTimeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evaluated For {0} Days benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FormatTotalDaysUsed {
            get {
                return ResourceManager.GetString("FormatTotalDaysUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The custom date format must be from the available list. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidCustomDateFormat {
            get {
                return ResourceManager.GetString("InvalidCustomDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Actions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelAllActions {
            get {
                return ResourceManager.GetString("LabelAllActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Colour benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelColor {
            get {
                return ResourceManager.GetString("LabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Offline) Values shown may not be accurate, and changes may not be saved. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelConfigurationWarningOffline {
            get {
                return ResourceManager.GetString("LabelConfigurationWarningOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evaluation benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelEvaluation {
            get {
                return ResourceManager.GetString("LabelEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Evaluation ({0} days) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelEvaluationWithDays {
            get {
                return ResourceManager.GetString("LabelEvaluationWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelImport {
            get {
                return ResourceManager.GetString("LabelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Large benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelLarge {
            get {
                return ResourceManager.GetString("LabelLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medium benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelMedium {
            get {
                return ResourceManager.GetString("LabelMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monochrome benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelMonochrome {
            get {
                return ResourceManager.GetString("LabelMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Group benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelNewGroup {
            get {
                return ResourceManager.GetString("LabelNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bluemed is ready to use benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelNotForDiagnosticUse {
            get {
                return ResourceManager.GetString("LabelNotForDiagnosticUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not for Human Diagnosis benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelNotForHumanDiagnosis {
            get {
                return ResourceManager.GetString("LabelNotForHumanDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelReset {
            get {
                return ResourceManager.GetString("LabelReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset All benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelResetAll {
            get {
                return ResourceManager.GetString("LabelResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save All benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelSaveAll {
            get {
                return ResourceManager.GetString("LabelSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Separator) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelSeparator {
            get {
                return ResourceManager.GetString("LabelSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LabelSmall {
            get {
                return ResourceManager.GetString("LabelSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alerts benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuAlertViewer {
            get {
                return ResourceManager.GetString("MenuAlertViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuCloseWindow {
            get {
                return ResourceManager.GetString("MenuCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Workspace benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuCloseWorkspace {
            get {
                return ResourceManager.GetString("MenuCloseWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings Editor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuConfigureSettings {
            get {
                return ResourceManager.GetString("MenuConfigureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contents benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuContents {
            get {
                return ResourceManager.GetString("MenuContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;File benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Help benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuIndex {
            get {
                return ResourceManager.GetString("MenuIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Group After benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuInsertGroupAfter {
            get {
                return ResourceManager.GetString("MenuInsertGroupAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Group benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuInsertGroupAsChild {
            get {
                return ResourceManager.GetString("MenuInsertGroupAsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Group Before benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuInsertGroupBefore {
            get {
                return ResourceManager.GetString("MenuInsertGroupBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Separator After benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuInsertSeparatorAfter {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Separator benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuInsertSeparatorAsChild {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorAsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Separator Before benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuInsertSeparatorBefore {
            get {
                return ResourceManager.GetString("MenuInsertSeparatorBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferences benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Tools benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuTools {
            get {
                return ResourceManager.GetString("MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Utilities benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuUtilities {
            get {
                return ResourceManager.GetString("MenuUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The background task is still running.  Are you sure you want to cancel? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageConfirmCancelTask {
            get {
                return ResourceManager.GetString("MessageConfirmCancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data has been modified and changes will be lost.  Discard changes and close? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageConfirmDiscardChangesBeforeClosing {
            get {
                return ResourceManager.GetString("MessageConfirmDiscardChangesBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import settings meta-data defined in locally installed plugins? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageConfirmImportSettingsMetaData {
            get {
                return ResourceManager.GetString("MessageConfirmImportSettingsMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application must restart in order to apply the new display language. Would you like to restart now? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageDisplayLanguageChangedRestartRequired {
            get {
                return ResourceManager.GetString("MessageDisplayLanguageChangedRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No configuration pages exist. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageNoConfigurationPagesExist {
            get {
                return ResourceManager.GetString("MessageNoConfigurationPagesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This group contains one or more items. Items may not be deleted, but can be hidden. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageNodeNotEmpty {
            get {
                return ResourceManager.GetString("MessageNodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset this setting back to its default value? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageReset {
            get {
                return ResourceManager.GetString("MessageReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset all settings back to default values? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageResetAll {
            get {
                return ResourceManager.GetString("MessageResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings have been modified.  Save changes? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageSaveModified {
            get {
                return ResourceManager.GetString("MessageSaveModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save the selected settings values.  Please ensure the values entered are properly formatted for the data type. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageSaveSettingFailed {
            get {
                return ResourceManager.GetString("MessageSaveSettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The settings store is currently offline.  Please try again later. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageSettingsStoreOffline {
            get {
                return ResourceManager.GetString("MessageSettingsStoreOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred which prevents the further use of this application. This application will now shut down to prevent damage to the system. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUnexpectedErrorQuit {
            get {
                return ResourceManager.GetString("MessageUnexpectedErrorQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unrecognized format benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUnrecognizedFormat {
            get {
                return ResourceManager.GetString("MessageUnrecognizedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating your personal preferences ... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUpdatingPreferences {
            get {
                return ResourceManager.GetString("MessageUpdatingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One or more errors have occurred while updating your preferences.  Some of your preferences may not have been properly configured. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageUserUpgradeFailures {
            get {
                return ResourceManager.GetString("MessageUserUpgradeFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value required benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessageValueRequired {
            get {
                return ResourceManager.GetString("MessageValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alerts benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleAlertViewer {
            get {
                return ResourceManager.GetString("TitleAlertViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleCancel {
            get {
                return ResourceManager.GetString("TitleCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleClose {
            get {
                return ResourceManager.GetString("TitleClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close Assistant benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleCloseAssistant {
            get {
                return ResourceManager.GetString("TitleCloseAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date Format benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleDateFormat {
            get {
                return ResourceManager.GetString("TitleDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Value benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleDefaultValue {
            get {
                return ResourceManager.GetString("TitleDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Value benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleEditValue {
            get {
                return ResourceManager.GetString("TitleEditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleGroup {
            get {
                return ResourceManager.GetString("TitleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferences benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleMenuOptions {
            get {
                return ResourceManager.GetString("TitleMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleNext {
            get {
                return ResourceManager.GetString("TitleNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitlePrevious {
            get {
                return ResourceManager.GetString("TitlePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleProperty {
            get {
                return ResourceManager.GetString("TitleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleRename {
            get {
                return ResourceManager.GetString("TitleRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scope benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleScope {
            get {
                return ResourceManager.GetString("TitleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings Editor benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleSettingsEditor {
            get {
                return ResourceManager.GetString("TitleSettingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toolbar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleToolbar {
            get {
                return ResourceManager.GetString("TitleToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleType {
            get {
                return ResourceManager.GetString("TitleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating Preferences ... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleUpdatingPreferences {
            get {
                return ResourceManager.GetString("TitleUpdatingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleValue {
            get {
                return ResourceManager.GetString("TitleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TitleVersion {
            get {
                return ResourceManager.GetString("TitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Group benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarAddGroup {
            get {
                return ResourceManager.GetString("ToolbarAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Separator benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarAddSeparator {
            get {
                return ResourceManager.GetString("ToolbarAddSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarRemove {
            get {
                return ResourceManager.GetString("ToolbarRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ToolbarRename {
            get {
                return ResourceManager.GetString("ToolbarRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can configure this item, but you do not have permission to use it. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipActionNotPermitted {
            get {
                return ResourceManager.GetString("TooltipActionNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}:
        ///You can configure this item, but you do not have permission to use it. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipFormatActionNotPermitted {
            get {
                return ResourceManager.GetString("TooltipFormatActionNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import settings meta-data from local plugins benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TooltipImportSettingsMetaData {
            get {
                return ResourceManager.GetString("TooltipImportSettingsMetaData", resourceCulture);
            }
        }
    }
}
